Repository tyquill/tyquill-ext-client, pull requests merged in 2025-09, with the labels that each got.

#50 [CHI-285] 스크랩 페이지에 PDF 업로드 UI 구현
  package.json
  pnpm-lock.yaml
  src/sidepanel/pages/PageStyles.module.css
  src/sidepanel/pages/ScrapPage.module.css
  src/sidepanel/pages/ScrapPage.tsx
Labels: feature, design

#53 Iss/chi 305
  .wxt/types/paths.d.ts
  entrypoints/webviewer/index.html
  entrypoints/webviewer/main.tsx
  src/sidepanel/pages/PageStyles.module.css
  src/sidepanel/pages/ScrapPage.tsx
  src/webviewer/App.tsx
  src/webviewer/ScrapView.tsx
  src/webviewer/UploadView.tsx
  wxt.config.ts
Labels: feature

#56 [CHI-316] 뉴스레터 생성 시 PDF 를 참고자료로 추가
  src/components/sidepanel/PDFUploadModal/PDFUploadModal.tsx
  src/config/environment.ts
  src/services/articleService.ts
  src/services/uploadService.ts
  src/sidepanel/pages/ArticleGeneratePage.module.css
  src/sidepanel/pages/ArticleGeneratePage.tsx
Labels: feature

#61 [FE] Tiptap 편집기 관련 경고 해결
  src/components/sidepanel/Editor/Editor.tsx
Labels: bug

#66 [CHI-360] 몇몇 페이지에서 스크랩이 되지 않는 문제 해결
  .gitignore
  src/utils/webClipper.ts
Labels: bug

#69 [CHI-269] 웹 클리핑, 메타데이터 기능 개선 및 추가
  package.json
  pnpm-lock.yaml
  src/content/App.tsx
  src/services/scrapService.ts
  src/sidepanel/pages/ScrapPage.tsx
  src/utils/webClipper.ts
Labels: feature
